BEGIN
   FOR r IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/


-- Słowniki --

CREATE TABLE S_Typy_Biurek (
    id_typu_biurka NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_typu VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE S_Statusy_Usterki (
    id_statusu_usterki NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_statusu VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE S_Statusy_Rezerwacji (
    id_statusu_rez NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_statusu VARCHAR2(50) UNIQUE NOT NULL
);


-- Tabele --

CREATE TABLE Budynki (
    id_budynku NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa VARCHAR2(100) NOT NULL,
    adres VARCHAR2(255)
);

CREATE TABLE Pietra (
    id_pietra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_budynku NUMBER REFERENCES Budynki(id_budynku),
    numer_pietra NUMBER NOT NULL,
    opis_strefy VARCHAR2(100)
);

CREATE TABLE Biurka (
    id_biurka NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pietra NUMBER REFERENCES Pietra(id_pietra),
    kod_biurka VARCHAR2(20) UNIQUE,
    id_typu_biurka NUMBER REFERENCES S_Typy_Biurek(id_typu_biurka),
    czy_sprawne NUMBER(1) DEFAULT 1
);

CREATE TABLE Departamenty (
    id_departamentu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa_dept VARCHAR2(100) NOT NULL,
    kod_budzetowy VARCHAR2(20)
);

CREATE TABLE Pracownicy (
    id_pracownika NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imie VARCHAR2(50),
    nazwisko VARCHAR2(50),
    email VARCHAR2(100) UNIQUE,
    id_departamentu NUMBER REFERENCES Departamenty(id_departamentu)
);

CREATE TABLE Biurka (
    id_biurka NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pietra NUMBER REFERENCES Pietra(id_pietra),
    kod_biurka VARCHAR2(20) UNIQUE,
    id_typu_biurka NUMBER REFERENCES S_Typy_Biurek(id_typu_biurka),
    czy_sprawne NUMBER(1) DEFAULT 1
);

CREATE TABLE Wyposazenie (
    id_sprzetu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_biurka NUMBER REFERENCES Biurka(id_biurka),
    nazwa_sprzetu VARCHAR2(100),
    numer_seryjny VARCHAR2(50)
);

CREATE TABLE Rezerwacje (
    id_rezerwacji NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pracownika NUMBER REFERENCES Pracownicy(id_pracownika),
    id_biurka NUMBER REFERENCES Biurka(id_biurka),
    data_rezerwacji DATE NOT NULL,
    id_statusu_rez NUMBER REFERENCES S_Statusy_Rezerwacji(id_statusu_rez),
    data_utworzenia TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Strefy_Dostepu (
    id_strefy NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamentu NUMBER REFERENCES Departamenty(id_departamentu),
    id_pietra NUMBER REFERENCES Pietra(id_pietra)
);

CREATE TABLE Usterki (
    id_usterki NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_biurka NUMBER REFERENCES Biurka(id_biurka),
    opis_usterki VARCHAR2(500),
    id_statusu_usterki NUMBER REFERENCES S_Statusy_Usterki(id_statusu_usterki),
    data_zgloszenia TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Miejsca_Parkingowe (
    id_miejsca NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_budynku NUMBER REFERENCES Budynki(id_budynku),
    nr_miejsca VARCHAR2(10)
);

CREATE TABLE Rezerwacje_Parking (
    id_rezerwacji_p NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pracownika NUMBER REFERENCES Pracownicy(id_pracownika),
    id_miejsca NUMBER REFERENCES Miejsca_Parkingowe(id_miejsca),
    data_parkowania DATE
);

CREATE TABLE Logi_Rezerwacji (
    id_logu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rezerwacji NUMBER,
    operacja VARCHAR2(20),
    uzytkownik VARCHAR2(100),
    data_operacji TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    stary_status VARCHAR2(20),
    nowy_status VARCHAR2(20)
);


-- Funkcje --

CREATE OR REPLACE FUNCTION F_CZY_MA_DOSTEP(
    p_pracownik_id IN NUMBER,
    p_biurko_id IN NUMBER
) RETURN NUMBER IS
    v_dept_pracownika NUMBER;
    v_pietro_biurka NUMBER;
    v_count NUMBER;
BEGIN
    SELECT id_departamentu INTO v_dept_pracownika FROM Pracownicy WHERE id_pracownika = p_pracownik_id;
    SELECT id_pietra INTO v_pietro_biurka FROM Biurka WHERE id_biurka = p_biurko_id;
    
    SELECT COUNT(*) INTO v_count FROM Strefy_Dostepu 
    WHERE id_departamentu = v_dept_pracownika AND id_pietra = v_pietro_biurka;
    
    RETURN v_count;
END;


-- Procedury --

CREATE OR REPLACE PROCEDURE P_PROCES_REZERWACJI(
    p_emp_id IN NUMBER,
    p_desk_id IN NUMBER,
    p_date IN DATE
) AS
    v_status_rez_id NUMBER;
    v_czy_sprawne NUMBER;
    v_zajete NUMBER;
BEGIN
    SELECT id_statusu_rez INTO v_status_rez_id FROM S_Statusy_Rezerwacji WHERE nazwa_statusu = 'PLANOWANA';

    SELECT czy_sprawne INTO v_czy_sprawne FROM Biurka WHERE id_biurka = p_desk_id FOR UPDATE;
    IF v_czy_sprawne = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Biurko uszkodzone.');
    END IF;

    SELECT COUNT(*) INTO v_zajete FROM Rezerwacje 
    WHERE id_biurka = p_desk_id AND data_rezerwacji = TRUNC(p_date);
    IF v_zajete > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Miejsce zajęte.');
    END IF;

    INSERT INTO Rezerwacje (id_pracownika, id_biurka, data_rezerwacji, id_statusu_rez)
    VALUES (p_emp_id, p_desk_id, TRUNC(p_date), v_status_rez_id);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;


-- Triggery --

CREATE OR REPLACE TRIGGER TR_AUDYT_REZERWACJI
AFTER INSERT OR DELETE ON Rezerwacje
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO Logi_Rezerwacji (id_rezerwacji, operacja, uzytkownik, nowy_status)
        VALUES (:NEW.id_rezerwacji, 'INSERT', USER, 'AKTYWNA');
    ELSIF DELETING THEN
        INSERT INTO Logi_Rezerwacji (id_rezerwacji, operacja, uzytkownik, stary_status)
        VALUES (:OLD.id_rezerwacji, 'DELETE', USER, 'USUNIETA');
    END IF;
END;

CREATE OR REPLACE TRIGGER TR_BLOKADA_HISTORII
BEFORE DELETE ON Rezerwacje
FOR EACH ROW
BEGIN
    IF :OLD.data_rezerwacji < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20010, 'Nie można usuwać rezerwacji z przeszłości!');
    END IF;
END;


-- Widoki --

CREATE OR REPLACE VIEW VW_RAPORT_OBLOZENIA AS
SELECT 
    b.nazwa as Budynek,
    COUNT(DISTINCT bi.id_biurka) as Wszystkie_Biurka,
    COUNT(r.id_rezerwacji) as Aktywne_Rezerwacje,
    ROUND((COUNT(r.id_rezerwacji) / NULLIF(COUNT(DISTINCT bi.id_biurka),0)) * 100, 2) as Procent_Oblozenia
FROM Budynki b
JOIN Pietra p ON b.id_budynku = p.id_budynku
JOIN Biurka bi ON p.id_pietra = bi.id_pietra
LEFT JOIN Rezerwacje r ON bi.id_biurka = r.id_biurka AND r.data_rezerwacji = TRUNC(SYSDATE)
GROUP BY b.nazwa;

CREATE OR REPLACE VIEW VW_BIURKA_PROBLEMATYCZNE AS
SELECT 
    bi.kod_biurka,
    u.opis_usterki,
    s.nazwa_statusu as Status_Usterki,
    u.data_zgloszenia
FROM Biurka bi
JOIN Usterki u ON bi.id_biurka = u.id_biurka
JOIN S_Statusy_Usterki s ON u.id_statusu_usterki = s.id_statusu_usterki;